apiVersion: v1
kind: Service
metadata:
  name: demoapp
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: demoapp
    app.kubernetes.io/part-of: dynatrace-demos
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: demoapp
  selector:
    app.kubernetes.io/component: demoapp
    app.kubernetes.io/part-of: dynatrace-demos
  type: LoadBalancer